### PR TITLE
Bringing FireFox extension up to par with Chrome

### PR DESCRIPTION
**Pull request by ptoonen**
Brought the FireFox extension up to par with the Chrome extension.

Updated jQuery to 3.5.1
Added Line endings to all files where possible as per recommendation
Removed height from panel because of flaky behavior in FireFox
Included charset in the HTML as per recommendation

o.. and fixed a typo in readme.txt ;-)

### CODE REVIEW

**Comment by ptoonen** [comment]
@AirLancer since #6 seems to be stale, I've submitted a new PR, hope you don't mind. I've brought the extension up to date and did some maintenance.

**Comment by steven-hack** [comment]
@AirLancer Any chance this PR could be completed? It looks fine, not a lot of changes and tested it myself and works perfectly. But as i rather not keep my signing setting on disabled, it would be nice if the update would be pushed through the official extension site.

**Review by AirLancer — APPROVED** [review]
Thank you for your patience and your contribution. It's not that the review is such a pain, but releasing a new version that annoys the hell out of me.
Though, my response time does not show it, I really appreciate the input.

**Comment by AirLancer** [comment]
> as i rather not keep my signing setting on disabled, it would be nice if the update would be pushed through the official extension site.

@ptoonen Done. I hope you don't mind the head nod towards you in the description.

**Pull request merged**
