### PR TITLE
Azure support for Firefox please

### PR DESCRIPTION
**Pull request by Regenhardt**
I'm not sure how this merge will work yet, but the changes look trivial enough.

### CODE REVIEW

**Comment by Regenhardt** [comment]
How do I solve this? Do I make a commit where i manually change the version from 2.0.1 to 2.2?

Also: Why not go the Firefox way for the default version? It should still work with the jquery/bootstrap files shipped wiht it, right?

**Comment by AirLancer** [comment]
Hi,
sorry for the late reply. I just started a new job. Quite the experience in the Corona-season :).
I'll have a look at getting the firefox extension on par with the chrome extension soon.
As to your question why not ship the dependencies: laziness.
I originally had both branches with the dependencies not included. Mozilla wouldn't allow it.
It is not that the inclusion of the dependencies is an issue, rather the release process is cumbersome.

**Comment by Regenhardt** [comment]
Good luck with your new job, you chose the hardest time ever to switch jobs lol. 
If you give me a quick explanation of how to resolve that conflict, I might be able to do it myself.

**Comment by AirLancer** [comment]
It looks to me as if you are trying to merge from my "master" branch on to the "firefox" branch (meaning you made changes directly on the master branch).
Ideally, you'd start by 

- creating your own branch which is **forked of the "firefox" branch**
  - Usually, you never devlop on the master branch. Technically, "firefox" is also a master branch, just for firefox (that is a bit wonky and you can blame me for it :).
Whenever you develop something, make a seperate branch for each feature/unit of work.

- make changes on your branch

- Do a PR to my "firefox" branch

This should prevent the merge issues. The current merge issue is because the manifest.json from master (chrome) isn't the same as the one for firefox.
I'd be thankfull if you could increase the version number in the manifest.json to "2.1.0" .

I totally understand if this is too much overhead and won't hold it against you if you leave the rest to me :).

As for the new job, it's smoother than expected. Worst part is missing out on meeting my new colleagues in person.

**Comment by AirLancer** [comment]
Is obsolete know with PR #8  by @ptoonen

**Pull request closed without merging**
